import { businessClock } from "./businessClock";
export const businessDate=()=>businessClock.snapshot();
export const percent=(v:number|null|undefined,digits=0)=>v==null?"—":new Intl.NumberFormat("tr-TR",{style:"percent",maximumFractionDigits:digits}).format(v);
export const decimal=(v:number|null|undefined,digits=2)=>v==null?"—":new Intl.NumberFormat("tr-TR",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(v);
export const money=(cents:number|null|undefined)=>cents==null?"—":new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(cents/100);
export const localDate=(v:string|null|undefined,withDate=false)=>!v?"—":new Intl.DateTimeFormat("tr-TR",withDate?{dateStyle:"medium",timeStyle:"short"}:{hour:"2-digit",minute:"2-digit"}).format(new Date(v));
export const marketLabel=(market:string,selection?:string,line?:number|null)=>({MATCH_RESULT:`Maç sonucu ${selection==="HOME"?"1":selection==="DRAW"?"X":selection==="AWAY"?"2":selection??""}`,BTTS:selection==="NO"?"KG Yok":"KG Var",TOTAL_GOALS:`${line??""} ${selection==="OVER"?"Üst":selection==="UNDER"?"Alt":selection??""}`.trim(),FULL_TIME_TOTAL_CORNERS:`Toplam Korner ${line??"(çizgi eksik)"} ${selection==="UNDER"?"Alt":selection==="OVER"?"Üst":selection??"(seçim eksik)"}`,CORNERS_TOTAL:`Toplam Korner ${line??"(çizgi eksik)"} ${selection==="UNDER"?"Alt":selection==="OVER"?"Üst":selection??"(seçim eksik)"}`,FULL_TIME_TOTAL_CARDS:`Kart ${line??""} ${selection==="UNDER"?"Alt":"Üst"}`}[market]??`${market} ${selection??""}`);
export const categoryLabel=(value:string)=>({CORNERS:"Korner",OVER_25:"2.5 Üst",OVER_35:"3.5 Üst",BTTS_YES:"KG Var",HIGH_CONFIDENCE:"Yüksek Güven",SURPRISE:"Sürpriz",COMPOUND:"Katlama",DAILY_CORNERS:"Korner",DAILY_OVER_25:"2.5 Üst",DAILY_OVER_35:"3.5 Üst",DAILY_BTTS:"KG Var",DAILY_HIGH_CONFIDENCE:"Yüksek Güven",DAILY_SURPRISE_SYSTEM:"Sürpriz Sistem",DAILY_COMPOUND:"Katlama"}[value]??value);
export const performanceMarketLabel=(value:string|null|undefined)=>value?({MATCH_RESULT:"Maç sonucu",BTTS:"KG Var",TOTAL_GOALS:"Toplam gol",TEAM_TOTAL_GOALS:"Takım toplam gol",FULL_TIME_TOTAL_CORNERS:"Toplam korner",FULL_TIME_TOTAL_CARDS:"Toplam kart"}[value]??value):"Tümü";
export const contextLabel=(value:string)=>({BASE:"BASE",LINEUP_AWARE:"11'ler sonrası",BASE_RETAINED:"BASE korundu"}[value]??value);
export const windowLabel=(value:string)=>({LAST_7_DAYS:"Son 7 gün",LAST_30_DAYS:"Son 30 gün",SEASON:"Sezon",ALL_TIME:"Tüm zamanlar"}[value]??value);
export const friendlyError=(error:string)=>error.includes("TAURI")||error.includes("BACKEND")?"Masaüstü veri servisine ulaşılamadı.":error.includes("NO_")?"Bu görünüm için henüz yeterli veri yok.":"Veriler alınırken bir sorun oluştu.";

export const exclusionLabel=(reason:string)=>({MODEL_UNSUPPORTED:"Model kapsamı dışında",RESOLUTION_FAILED:"Kanonik eşleşme sorunu",INSUFFICIENT_HISTORY:"Yetersiz maç geçmişi",MODEL_PREDICTION_UNAVAILABLE:"Model tahmini henüz hazırlanmadı",INVALID_ODDS:"Geçerli oynanabilir oran yok",ODDS_UNAVAILABLE:"Bu seçim için oran yok",STALE_ODDS:"Oran güncel değil",LOW_PUBLIC_PROBABILITY:"Olasılık politika altında",LOW_EDGE:"Model avantajı yetersiz",LOW_EV:"Beklenen değer yetersiz",UNSUPPORTED_MARKET:"Kategoriye uygun pazar değil",ODDS_MARKET_UNAVAILABLE:"Kategoriye uygun oran yok",LOW_DATA_QUALITY:"Geçmiş veri kalitesi yetersiz",MATCH_STARTED:"Maç başladı",MATCH_FINISHED:"Maç tamamlandı",CORRELATION_REDUCTION:"Aynı maçtan seçim sınırı",CALIBRATION_INSUFFICIENT:"Kalibrasyon desteği yetersiz",INSUFFICIENT_BUCKET_SAMPLE:"Kalibrasyon örnek sayısı yetersiz",KICKOFF_UNKNOWN:"Başlama saati doğrulanmamış",INVALID_PROBABILITY:"Model olasılığı geçersiz",NEGATIVE_MODEL_QUALITY:"Belirgin model kalitesi sorunu"}[reason]??reason);

export const readinessLabel=(x:string)=>({READY:"HAZIR",OPTIONAL:"İsteğe bağlı",BACKGROUND:"Arka planda tamamlanıyor",PARTIAL:"Kısmen hazır",ACTION_REQUIRED:"Müdahale gerekiyor",UPDATING:"Hazırlanıyor",ERROR:"Müdahale gerekiyor",UNAVAILABLE:"Kullanılamıyor"}[x]??"Hazırlık denetleniyor");
