CREATE INDEX idx_performance_finished_date ON matches(date(kickoff_at,'+3 hours'),id) WHERE status='finished';
CREATE INDEX idx_performance_backtest_match ON backtest_calibration_predictions(match_id,settlement);
CREATE INDEX idx_performance_odds_lookup ON odds_snapshots(match_id,UPPER(COALESCE(normalized_market_type,market_name)),UPPER(COALESCE(normalized_selection,selection)),captured_at DESC,id DESC);
CREATE TABLE model_performance_epoch(id INTEGER PRIMARY KEY CHECK(id=1),version INTEGER NOT NULL);
INSERT INTO model_performance_epoch VALUES(1,0);
CREATE TRIGGER performance_epoch_backtest_calibration_predictions_insert AFTER INSERT ON backtest_calibration_predictions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_backtest_calibration_predictions_update AFTER UPDATE ON backtest_calibration_predictions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_backtest_calibration_predictions_delete AFTER DELETE ON backtest_calibration_predictions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_backtest_runs_insert AFTER INSERT ON backtest_runs BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_backtest_runs_update AFTER UPDATE ON backtest_runs BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_backtest_runs_delete AFTER DELETE ON backtest_runs BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_calibration_models_insert AFTER INSERT ON calibration_models BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_calibration_models_update AFTER UPDATE ON calibration_models BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_calibration_models_delete AFTER DELETE ON calibration_models BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_matches_insert AFTER INSERT ON matches BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_matches_update AFTER UPDATE ON matches BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_matches_delete AFTER DELETE ON matches BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_competitions_insert AFTER INSERT ON competitions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_competitions_update AFTER UPDATE ON competitions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_competitions_delete AFTER DELETE ON competitions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_match_statistics_insert AFTER INSERT ON match_statistics BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_match_statistics_update AFTER UPDATE ON match_statistics BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_match_statistics_delete AFTER DELETE ON match_statistics BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_odds_snapshots_insert AFTER INSERT ON odds_snapshots BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_odds_snapshots_update AFTER UPDATE ON odds_snapshots BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_odds_snapshots_delete AFTER DELETE ON odds_snapshots BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_prediction_revisions_insert AFTER INSERT ON prediction_revisions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_prediction_revisions_update AFTER UPDATE ON prediction_revisions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_prediction_revisions_delete AFTER DELETE ON prediction_revisions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_candidate_engine_candidates_insert AFTER INSERT ON candidate_engine_candidates BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_candidate_engine_candidates_update AFTER UPDATE ON candidate_engine_candidates BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_candidate_engine_candidates_delete AFTER DELETE ON candidate_engine_candidates BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_candidate_engine_runs_insert AFTER INSERT ON candidate_engine_runs BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_candidate_engine_runs_update AFTER UPDATE ON candidate_engine_runs BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_candidate_engine_runs_delete AFTER DELETE ON candidate_engine_runs BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
