DROP TRIGGER performance_epoch_backtest_calibration_predictions_insert;
CREATE TRIGGER performance_epoch_backtest_calibration_predictions_insert AFTER INSERT ON backtest_calibration_predictions  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_backtest_calibration_predictions_update;
CREATE TRIGGER performance_epoch_backtest_calibration_predictions_update AFTER UPDATE ON backtest_calibration_predictions  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_backtest_calibration_predictions_delete;
CREATE TRIGGER performance_epoch_backtest_calibration_predictions_delete AFTER DELETE ON backtest_calibration_predictions  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_backtest_runs_insert;
CREATE TRIGGER performance_epoch_backtest_runs_insert AFTER INSERT ON backtest_runs  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_backtest_runs_update;
CREATE TRIGGER performance_epoch_backtest_runs_update AFTER UPDATE ON backtest_runs  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_backtest_runs_delete;
CREATE TRIGGER performance_epoch_backtest_runs_delete AFTER DELETE ON backtest_runs  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_calibration_models_insert;
CREATE TRIGGER performance_epoch_calibration_models_insert AFTER INSERT ON calibration_models  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_calibration_models_update;
CREATE TRIGGER performance_epoch_calibration_models_update AFTER UPDATE ON calibration_models  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_calibration_models_delete;
CREATE TRIGGER performance_epoch_calibration_models_delete AFTER DELETE ON calibration_models  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_matches_insert;
CREATE TRIGGER performance_epoch_matches_insert AFTER INSERT ON matches WHEN NEW.status='finished' BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_matches_update;
CREATE TRIGGER performance_epoch_matches_update AFTER UPDATE ON matches WHEN (OLD.status='finished' OR NEW.status='finished') AND (OLD.status IS NOT NEW.status OR OLD.kickoff_at IS NOT NEW.kickoff_at OR OLD.season IS NOT NEW.season OR OLD.competition_id IS NOT NEW.competition_id OR OLD.final_home_goals IS NOT NEW.final_home_goals OR OLD.final_away_goals IS NOT NEW.final_away_goals) BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_matches_delete;
CREATE TRIGGER performance_epoch_matches_delete AFTER DELETE ON matches WHEN OLD.status='finished' BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_competitions_insert;
CREATE TRIGGER performance_epoch_competitions_insert AFTER INSERT ON competitions  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_competitions_update;
CREATE TRIGGER performance_epoch_competitions_update AFTER UPDATE ON competitions  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_competitions_delete;
CREATE TRIGGER performance_epoch_competitions_delete AFTER DELETE ON competitions  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_match_statistics_insert;
CREATE TRIGGER performance_epoch_match_statistics_insert AFTER INSERT ON match_statistics  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_match_statistics_update;
CREATE TRIGGER performance_epoch_match_statistics_update AFTER UPDATE ON match_statistics WHEN OLD.home_corners IS NOT NEW.home_corners OR OLD.away_corners IS NOT NEW.away_corners OR OLD.home_yellow_cards IS NOT NEW.home_yellow_cards OR OLD.away_yellow_cards IS NOT NEW.away_yellow_cards BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_match_statistics_delete;
CREATE TRIGGER performance_epoch_match_statistics_delete AFTER DELETE ON match_statistics  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_odds_snapshots_insert;
CREATE TRIGGER performance_epoch_odds_snapshots_insert AFTER INSERT ON odds_snapshots WHEN EXISTS(SELECT 1 FROM matches WHERE id=NEW.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_odds_snapshots_update;
CREATE TRIGGER performance_epoch_odds_snapshots_update AFTER UPDATE ON odds_snapshots WHEN EXISTS(SELECT 1 FROM matches WHERE id=NEW.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_odds_snapshots_delete;
CREATE TRIGGER performance_epoch_odds_snapshots_delete AFTER DELETE ON odds_snapshots WHEN EXISTS(SELECT 1 FROM matches WHERE id=OLD.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_prediction_revisions_insert;
CREATE TRIGGER performance_epoch_prediction_revisions_insert AFTER INSERT ON prediction_revisions WHEN EXISTS(SELECT 1 FROM matches WHERE id=NEW.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_prediction_revisions_update;
CREATE TRIGGER performance_epoch_prediction_revisions_update AFTER UPDATE ON prediction_revisions WHEN EXISTS(SELECT 1 FROM matches WHERE id=NEW.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_prediction_revisions_delete;
CREATE TRIGGER performance_epoch_prediction_revisions_delete AFTER DELETE ON prediction_revisions WHEN EXISTS(SELECT 1 FROM matches WHERE id=OLD.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_candidate_engine_candidates_insert;
CREATE TRIGGER performance_epoch_candidate_engine_candidates_insert AFTER INSERT ON candidate_engine_candidates WHEN EXISTS(SELECT 1 FROM matches WHERE id=NEW.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_candidate_engine_candidates_update;
CREATE TRIGGER performance_epoch_candidate_engine_candidates_update AFTER UPDATE ON candidate_engine_candidates WHEN EXISTS(SELECT 1 FROM matches WHERE id=NEW.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_candidate_engine_candidates_delete;
CREATE TRIGGER performance_epoch_candidate_engine_candidates_delete AFTER DELETE ON candidate_engine_candidates WHEN EXISTS(SELECT 1 FROM matches WHERE id=OLD.match_id AND status='finished') BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_candidate_engine_runs_insert;
CREATE TRIGGER performance_epoch_candidate_engine_runs_insert AFTER INSERT ON candidate_engine_runs  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_candidate_engine_runs_update;
CREATE TRIGGER performance_epoch_candidate_engine_runs_update AFTER UPDATE ON candidate_engine_runs  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
DROP TRIGGER performance_epoch_candidate_engine_runs_delete;
CREATE TRIGGER performance_epoch_candidate_engine_runs_delete AFTER DELETE ON candidate_engine_runs  BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_model_versions_insert AFTER INSERT ON model_versions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_model_versions_update AFTER UPDATE ON model_versions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
CREATE TRIGGER performance_epoch_model_versions_delete AFTER DELETE ON model_versions BEGIN UPDATE model_performance_epoch SET version=version+1 WHERE id=1; END;
