import { useBusinessDate } from "../hooks/useBusinessDate";
import { dailySelections, selectedContext } from "../lib/dailySelections";
import { relevantCategoryExclusion } from "../lib/goalExclusions";
import { useState } from "react";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/tauri";
import { categoryLabel, percent, exclusionLabel } from "../lib/format";
import { DataState, EmptyState } from "../components/States";
import { MatchRow } from "../components/MatchRow";
import { PageHeader } from "../components/Page";
import { StatusBadge } from "../components/StatusBadge";
const categories=["TÜMÜ","CORNERS","OVER_25","OVER_35","BTTS_YES","HIGH_CONFIDENCE","SURPRISE","COMPOUND"];
export function CandidatesPage(){
 const date=useBusinessDate(); const [category,setCategory]=useState("TÜMÜ");
 const state=useAsync(async()=>{const [run,matches]=await Promise.all([api.candidates(date).catch(e=>{if(e.message==='no candidate run')return null;throw e}),api.dailyMatches(date)]);return{run,matches}},[date]);
 return <><PageHeader eyebrow="GÜNLÜK MODEL SEÇİMLERİ" title="Günün Adayları" description="Kuponlarla ortak günlük havuz. Nitelikli seçimler ve günlük sıralamalar ayrı işaretlenir." actions={<button className="button secondary" onClick={state.reload}>Yenile</button>}/><div className="filterbar category-filters" role="group" aria-label="Kategori filtresi">{categories.map(x=><button key={x} data-category={x} className={category===x?"active":""} onClick={()=>setCategory(x)}>{x==="TÜMÜ"?"Tümü":categoryLabel(x)}{state.data?.run&&` (${dailySelections(state.data.run,x).length})`}</button>)}</div><DataState {...state} onRetry={state.reload}>{({run,matches})=>{if(!run)return <section className="panel"><EmptyState title="Bugün yeterli güvene sahip aday yok." detail="Yeni aday çalıştırması oluştuğunda burada görünecek."/></section>;const items=dailySelections(run,category);const reasons=Object.entries((run.exclusions??[]).reduce<Record<string,Set<number>>>((a,e)=>{if(e.match_id!=null&&relevantCategoryExclusion(e,category))(a[e.reason]??=new Set()).add(e.match_id);return a},{}));return <section className="panel" data-publication={run.publication_id}><div className="context-strip"><div><StatusBadge value={selectedContext(run)}/>{selectedContext(run)==="LINEUP_AWARE"&&<span>11’ler sonrası güncellendi</span>}</div><span>{items.length} aday · Çalıştırma #{run.run_id}</span></div><div className="context-strip"><small>Yayın {run.publication_id} · {category==="TÜMÜ"?"Tekil günlük seçimler":`Kaynak #${run.category_run_ids?.[category]??run.run_id}`} · {run.model_version}</small></div>{items.length?<div className="candidate-grid">{items.map(c=><div key={c.id} data-candidate-id={c.id} className="candidate-wrap"><MatchRow candidate={c} match={matches.find(m=>m.match_id===c.match_id)}/>{c.base_public_probability!=null&&c.final_public_probability!=null&&c.base_public_probability!==c.final_public_probability&&<div className="lineup-delta">BASE {percent(c.base_public_probability,1)} <span>→</span> Güncel {percent(c.final_public_probability,1)}</div>}{c.prediction_source==="BASE_RETAINED"&&<small className="retained-note">11 bilgisi mevcut, model fayda görmedi; BASE korundu.</small>}</div>)}</div>:<EmptyState title="Bu tarih ve kategori için yayınlanmış seçim yok."/>}{reasons.length>0&&<details className="details" open={items.length===0}><summary>Uygunluk değerlendirmesi: {run.match_count_considered} maç</summary>{reasons.map(([reason,ids])=><div key={reason}>{exclusionLabel(reason)}: {ids.size} maç</div>)}</details>}</section>}}</DataState></>
}
