import { useAsync } from "../hooks/useAsync";
import { api } from "../services/tauri";
import { businessDate, decimal, marketLabel, money, percent } from "../lib/format";
import type { CompoundSeries, Coupon, LineupImpact, UpcomingMatch } from "../types";
import { DataState, EmptyState } from "../components/States";
import { PageHeader } from "../components/Page";
import { StatusBadge } from "../components/StatusBadge";
const kinds=["DAILY_CORNERS","DAILY_OVER_25","DAILY_OVER_35","DAILY_BTTS","DAILY_HIGH_CONFIDENCE","DAILY_SURPRISE_SYSTEM","DAILY_COMPOUND"];
const names:Record<string,string>={DAILY_CORNERS:"Günün Korner Kuponu",DAILY_OVER_25:"Günün 2.5 Üst Kuponu",DAILY_OVER_35:"Günün 3.5 Üst Kuponu",DAILY_BTTS:"Günün KG Var Kuponu",DAILY_HIGH_CONFIDENCE:"Günün Yüksek Güven Kuponu",DAILY_SURPRISE_SYSTEM:"Günün Sürpriz Kuponu",DAILY_COMPOUND:"Günün Katlama Kuponu"};
export function CouponsPage(){
 const date=businessDate();
 const state=useAsync(async()=>{const [coupons,matches,compound]=await Promise.all([api.coupons(date),api.matches(),api.compound()]);const impacts=new Map<number,LineupImpact>();await Promise.all(coupons.filter(x=>x.status==="DRAFT").map(async x=>{try{impacts.set(x.id,await api.couponImpact(x.id))}catch{/* impact unavailable */}}));return{coupons,matches,compound,impacts}},[date]);
 return <><PageHeader eyebrow="GÜNLÜK DONMUŞ KUPONLAR" title="Günün Kuponları" description="Kriterleri karşılayan kuponlar; zayıf seçimler istemci tarafında tamamlanmaz." actions={<button className="button secondary" onClick={state.reload}>Yenile</button>}/><DataState {...state} onRetry={state.reload}>{({coupons,matches,compound,impacts})=><div className="coupon-grid">{kinds.map(kind=><CouponCard key={kind} kind={kind} coupon={coupons.find(x=>x.coupon_type===kind)} matches={matches} impact={coupons.find(x=>x.coupon_type===kind)?impacts.get(coupons.find(x=>x.coupon_type===kind)!.id):undefined} compound={kind==="DAILY_COMPOUND"?compound:null}/>)}</div>}</DataState></>
}
function CouponCard({kind,coupon,matches,impact,compound}:{kind:string;coupon?:Coupon;matches:UpcomingMatch[];impact?:LineupImpact;compound:CompoundSeries|null}){
 if(!coupon)return <section className="panel coupon-card unavailable"><div className="coupon-title"><div><span className="eyebrow">GÜNLÜK</span><h2>{names[kind]}</h2></div><StatusBadge value="UNAVAILABLE"/></div><EmptyState title="Bugün kriterleri karşılayan kupon oluşturulamadı."/></section>;
 return <section className="panel coupon-card"><div className="coupon-title"><div><span className="eyebrow">{coupon.selections.length} SEÇİM</span><h2>{names[kind]}</h2></div><StatusBadge value={coupon.status}/></div>{impact?.revision_available&&<div className="impact-banner"><strong>11’ler sonrası bu kuponda değişiklik var.</strong><span>Taslak otomatik değiştirilmedi.</span></div>}<div className="coupon-lines">{coupon.selections.map(s=>{const m=matches.find(x=>x.match_id===s.match_id),change=impact?.items.find(x=>x.match_id===s.match_id&&x.market===s.market&&x.selection===s.selection);return <div className="coupon-line" key={s.candidate_id}><div><small>{m?.competition??`Maç #${s.match_id}`}</small><strong>{m?`${m.home_team} — ${m.away_team}`:marketLabel(s.market,s.selection,s.line)}</strong><span>{marketLabel(s.market,s.selection,s.line)}</span></div><div><strong>{percent(s.public_probability,1)}</strong><span>{decimal(s.odd)}</span></div>{change&&change.impact_type!=="UNCHANGED"&&<div className={`impact ${change.impact_type==="NO_LONGER_QUALIFIED"?"warning":""}`}><StatusBadge value={change.impact_type}/><span>{percent(change.base_probability,1)} → {percent(change.latest_probability,1)} ({change.delta_percentage_points>0?"+":""}{decimal(change.delta_percentage_points,1)} pp)</span></div>}</div>})}</div><div className="coupon-footer"><div><span>Toplam oran</span><strong>{decimal(coupon.combined_decimal_odd)}</strong></div><div><span>Toplam stake</span><strong>{money(coupon.total_stake_cents)}</strong></div>{coupon.system_sizes.length>0&&<div><span>Sistem</span><strong>{coupon.system_sizes.join(" / ")} · {coupon.columns.length} kolon</strong></div>}</div>{coupon.columns.length>0&&<details className="details"><summary>Kolon ayrıntıları</summary><div>{coupon.columns.map(x=><span key={x.column_number}>#{x.column_number} · Sistem {x.system_size} · {decimal(x.column_decimal_odd)} <StatusBadge value={x.status}/></span>)}</div></details>}{compound&&kind==="DAILY_COMPOUND"&&<KatlamaState series={compound}/>}</section>
}
function KatlamaState({series}:{series:CompoundSeries}){return <><div className="katlama-strip"><div><span>Adım</span><strong>{series.current_step} / 7</strong></div><div><span>Başlangıç</span><strong>{money(series.starting_stake_cents)}</strong></div><div><span>Güncel devreden tutar</span><strong>{money(series.current_stake_cents)}</strong></div><StatusBadge value={series.status}/></div>{series.history.length>0&&<details className="details"><summary>Önceki adımlar</summary><div>{series.history.map(x=><span key={x.coupon_id}>Adım {x.step_number} · {decimal(x.combined_odd)} · <StatusBadge value={x.result}/></span>)}</div></details>}</>}
