import { readyCoupons } from "../lib/readyCoupons";
import { useBusinessDate } from "../hooks/useBusinessDate";
import { relevantCategoryExclusion } from "../lib/goalExclusions";
import { BttsCouponCard } from "../components/BttsCouponCard";
import { useEffect, useState } from "react";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/tauri";
import { businessDate, decimal, marketLabel, money, percent, exclusionLabel } from "../lib/format";
import type { CompoundSeries, CompoundSearch, DailyRun, Coupon, LineupImpact, UpcomingMatch } from "../types";
import { DataState, EmptyState } from "../components/States";
import { PageHeader } from "../components/Page";
import { StatusBadge } from "../components/StatusBadge";
const kinds=["DAILY_CORNERS","DAILY_OVER_25","DAILY_OVER_35","DAILY_BTTS","DAILY_HIGH_CONFIDENCE","DAILY_SURPRISE_SYSTEM","DAILY_COMPOUND"];
const names:Record<string,string>={DAILY_CORNERS:"Günün Korner Kuponu",DAILY_OVER_25:"Günün 2.5 Üst Kuponu",DAILY_OVER_35:"Günün 3.5 Üst Kuponu",DAILY_BTTS:"Günün KG Var Kuponu",DAILY_HIGH_CONFIDENCE:"Günün Yüksek Güven Kuponu",DAILY_SURPRISE_SYSTEM:"Günün Sürpriz Kuponu",DAILY_COMPOUND:"Günün Katlama Kuponu"};
export function CouponsPage(){
 const date=useBusinessDate();
 const state=useAsync(async()=>{const [coupons,matches,compound,run,search]=await Promise.all([api.coupons(date),api.dailyMatches(date),api.compound(),api.candidates(date).catch(e=>{if(e.message==="no candidate run")return null;throw e}),api.compoundSearch(date).catch(()=>null)]);return{coupons:coupons.filter(c=>c.business_date===date),matches,compound,run,search}},[date]);
 useEffect(()=>{if(state.data){void api.prioritizeMatches([...new Set(state.data.coupons.flatMap(c=>c.selections.map(s=>s.match_id)))]).catch(()=>{});}},[state.data]);
 useEffect(()=>{const reload=()=>{void state.reload();};window.addEventListener("btts-updated",reload);return()=>window.removeEventListener("btts-updated",reload);},[state.reload]);
 return <><PageHeader eyebrow="GÜNLÜK DONMUŞ KUPONLAR" title="Günün Kuponları" description="Kriterleri karşılayan kuponlar; zayıf seçimler istemci tarafında tamamlanmaz." actions={<button className="button secondary" onClick={state.reload}>Yenile</button>}/><DataState {...state} onRetry={state.reload}>{({coupons,matches,compound,run,search})=><><div className="context-strip" data-publication={run?.publication_id}>Yayın {run?.publication_id} · {run?.prediction_context}</div><CompoundControls key={date} date={date} series={compound} onChange={state.reload}/><div className="coupon-grid">{readyCoupons(coupons).map(coupon=>{const kind=coupon.coupon_type;return <CouponCard key={coupon.id} run={run} search={kind==="DAILY_COMPOUND"?search:null} qualified={new Set((run?.candidates??[]).filter(c=>c.category===({DAILY_CORNERS:"CORNERS",DAILY_OVER_25:"OVER_25",DAILY_OVER_35:"OVER_35",DAILY_BTTS:"BTTS_YES",DAILY_HIGH_CONFIDENCE:"HIGH_CONFIDENCE",DAILY_SURPRISE_SYSTEM:"SURPRISE",DAILY_COMPOUND:"COMPOUND"}[kind])).map(c=>c.match_id)).size} kind={kind} coupon={coupon} matches={matches} compound={kind==="DAILY_COMPOUND"?compound:null}/>})}</div><details className="unavailable-coupons"><summary>Oluşturulamayan kuponlar</summary>{kinds.filter(kind=>!coupons.some(c=>c.coupon_type===kind&&c.publication_status==="READY")).map(kind=><div key={kind}><strong>{names[kind]}</strong><span>{coupons.find(c=>c.coupon_type===kind)?.publication_status??"INSUFFICIENT"}</span><GoalShortage kind={kind} run={run}/></div>)}</details></>}</DataState></>
}
function CouponCard({kind,coupon,matches,compound,qualified,run,search}:{run:DailyRun|null;search:CompoundSearch|null;qualified:number;kind:string;coupon?:Coupon;matches:UpcomingMatch[];impact?:LineupImpact;compound:CompoundSeries|null}){
 const check=useAsync(()=>api.couponImpact(coupon!.id),[coupon?.id],false),impact=check.data;
 if(kind==="DAILY_BTTS")return <BttsCouponCard date={run?.business_date??businessDate()} coupon={coupon} matches={matches}/>;
 if(!coupon)return <section className="panel coupon-card unavailable"><div className="coupon-title"><div><span className="eyebrow">GÜNLÜK</span><h2>{names[kind]}</h2></div><StatusBadge value={search?.chosen?"DRAFT":"INSUFFICIENT"}/></div><EmptyState title={search?.chosen?"Katlama birleşimi hazır":kind==="DAILY_CORNERS"?"Yeterli nitelikli korner adayı yok":"Yeterli nitelikli aday yok"} detail={search?.chosen?`${search.chosen.candidate_ids.length} seçim · ${decimal(search.chosen.combined_odd)} toplam oran. Seriyi başlatıp adım kuponunu hazırlayın.`:`${qualified} havuz seçimi / en az ${kind==="DAILY_COMPOUND"?2:kind==="DAILY_SURPRISE_SYSTEM"?6:kind==="DAILY_OVER_25"||kind==="DAILY_OVER_35"?3:5} gerekli. ${kind==="DAILY_COMPOUND"?qualified>=2?"Nitelikli seçimlerle 1,50–1,80 oran birleşimi yok; hedef 1,80.":"2–3 seçim, hedef toplam oran 1,80.":""}`}/><GoalShortage kind={kind} run={run}/>{search&&<SearchDetails search={search} run={run} matches={matches}/>} {kind==="DAILY_COMPOUND"&&(compound?<KatlamaState series={compound}/>:<div className="katlama-strip">Adım 1 / 7 · Seri başlatılmadı. Uygun seçim bekleniyor.</div>)}</section>;
 return <section className="panel coupon-card"><div className="coupon-title"><div><span className="eyebrow">{coupon.selections.length} SEÇİM{kind==="DAILY_COMPOUND"?` · ${coupon.business_date}`:""}</span><h2>{names[kind]}</h2></div><StatusBadge value={coupon.publication_status}/></div><button className="button secondary" onClick={check.reload} disabled={check.loading}>11 etkisini kontrol et</button>{check.error&&<span role="alert">{check.error}</span>}{impact?.revision_available&&<div className="impact-banner"><strong>11’ler sonrası bu kuponda değişiklik var.</strong><span>Taslak otomatik değiştirilmedi.</span></div>}<div className="coupon-lines">{coupon.selections.map(s=>{const m=matches.find(x=>x.match_id===s.match_id),change=impact?.items.find(x=>x.match_id===s.match_id&&x.market===s.market&&x.selection===s.selection);return <div className="coupon-line" key={s.candidate_id}><div><small>{m?.competition??`Maç #${s.match_id}`}</small><strong>{m?`${m.home_team} — ${m.away_team}`:marketLabel(s.market,s.selection,s.line)}</strong><span>{marketLabel(s.market,s.selection,s.line)}</span>{s.settlement_state==="PENDING_DATA"&&<small title={s.settlement_reason??undefined}>Sonuç verisi bekleniyor</small>}</div><div><strong>{percent(s.public_probability,1)}</strong><span>{decimal(s.odd)}</span></div>{change&&change.impact_type!=="UNCHANGED"&&<div className={`impact ${change.impact_type==="NO_LONGER_QUALIFIED"?"warning":""}`}><StatusBadge value={change.impact_type}/><span>{percent(change.base_probability,1)} → {percent(change.latest_probability,1)} ({change.delta_percentage_points>0?"+":""}{decimal(change.delta_percentage_points,1)} pp)</span></div>}</div>})}</div><div className="coupon-footer"><div><span>Toplam oran</span><strong>{decimal(coupon.combined_decimal_odd)}</strong></div><div><span>Toplam stake</span><strong>{money(coupon.total_stake_cents)}</strong></div>{coupon.system_sizes.length>0&&<div><span>Sistem</span><strong>{coupon.system_sizes.join(" / ")} · {coupon.columns.length} kolon</strong></div>}</div>{coupon.columns.length>0&&<details className="details"><summary>Kolon ayrıntıları</summary><div>{coupon.columns.map(x=><span key={x.column_number}>#{x.column_number} · Sistem {x.system_size} · {decimal(x.column_decimal_odd)} <StatusBadge value={x.status}/></span>)}</div></details>}{search&&<SearchDetails search={search} run={run} matches={matches}/>} {compound&&kind==="DAILY_COMPOUND"&&<KatlamaState series={compound}/>}</section>
}
function KatlamaState({series}:{series:CompoundSeries}){
 const previous=[...series.history].reverse().find(x=>x.result!=="UNSETTLED");
 const reason=previous?.result==="LOST"?"Kayıp sonrası adım 1’e sıfırlandı":previous?.step_number===7&&previous.result==="WON"?"7 adım tamamlandı; yeni döngü":previous?.result==="WON"?"Kesinleşmiş kazanç sonrası sonraki adıma geçildi":previous?.result==="VOID"?"İptal edilen adım aynı tutarla yeniden hazırlanır":"Sonuç kesinleşmeden ilerlemez";
 return <><div className="katlama-strip"><div><span>Adım</span><strong>{series.current_step} / 7</strong></div><div><span>Başlangıç</span><strong>{money(series.starting_stake_cents)}</strong></div><div><span>Güncel devreden tutar</span><strong>{money(series.current_stake_cents)}</strong></div><StatusBadge value={series.status}/></div><p>{previous?`Önceki sonuç: ${previous.result} · `:""}{reason}</p></>
}

function CompoundControls({date,series,onChange}:{date:string;series:CompoundSeries|null;onChange:()=>unknown}){
 const priorPending=series?.history.some(x=>x.result==="UNSETTLED"&&x.business_date!==date)??false;
 const [stake,setStake]=useState("100"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function act(){setBusy(true);setMessage("");try{if(!series||series.status!=="ACTIVE"){await api.startCompound(date,Math.round(Number(stake)*100));}else{await api.generateCompound(date);}await onChange();}catch(e){setMessage(e instanceof Error&&e.message==="NO_QUALIFYING_COMPOUND_COUPON"?"Bu gün için 2–3 nitelikli seçimle 1,50–1,80 oran oluşturulamıyor.":e instanceof Error?e.message:String(e));}finally{setBusy(false)}}
 return <div className="filterbar"><strong>Katlama · Adım {series?.current_step??1} / 7</strong>{!series||series.status!=="ACTIVE"?<label>Başlangıç tutarı <input aria-label="Katlama başlangıç tutarı" type="number" min="1" value={stake} onChange={e=>setStake(e.target.value)}/></label>:<span>Yalnızca kesinleşmiş kazanç sonrası ilerler.</span>}<button className="button secondary" disabled={busy||priorPending||(!series&&Number(stake)<=0)} onClick={act}>{busy?"İşleniyor…":priorPending?"Önceki adım sonuç bekliyor":series?.status==="ACTIVE"?"Adım kuponunu hazırla":"Seriyi başlat"}</button>{message&&<span role="status">{message}</span>}</div>
}

function SearchDetails({search,run,matches}:{search:CompoundSearch;run:DailyRun|null;matches:UpcomingMatch[]}){return <details className="details" open={!search.chosen}><summary>{run?.business_date} · Katlama araması: {search.pool_size} uygun aday · {search.pairs_evaluated} ikili / {search.triples_evaluated} üçlü</summary>{search.chosen&&<p>{run?.business_date} önerisi: {search.chosen.candidate_ids.length} seçim · toplam oran {decimal(search.chosen.combined_odd,4)}. Aktif, sonuçlanmamış adımın yerini almaz.</p>}<div>{search.chosen?.candidate_ids.map(id=>{const c=run?.candidates.find(x=>x.id===id),m=matches.find(x=>x.match_id===c?.match_id);return c?<p key={id}>{m?m.home_team+" — "+m.away_team:"Maç #"+c.match_id} · {marketLabel(c.market,c.selection,c.line)} · {decimal(c.iddaa_odd)} · {percent(c.public_probability,1)}</p>:null})}</div><p>{search.valid_combinations} geçerli birleşim · {search.correlated_rejected} aynı maç nedeniyle elendi.</p>{search.closest.map(([target,c])=><div key={target}>Hedef {decimal(target)}: {c?`${decimal(c.combined_odd,4)} · ${c.candidate_ids.length} seçim`:"Birleşim oluşturulamıyor"}</div>)}{search.reason==="SEARCH_LIMIT_REACHED"&&<p>256 aday arama sınırı aşıldı; tüm birleşimler incelenmeden yok sonucu verilmez.</p>}</details>}
function GoalShortage({kind,run}:{kind:string;run:DailyRun|null}) {
 const cat=({DAILY_OVER_25:"OVER_25",DAILY_OVER_35:"OVER_35",DAILY_BTTS:"BTTS_YES"} as Record<string,string>)[kind];
 if(!cat||!run)return null;
 const ranked=kind!=="DAILY_OVER_35"&&run.policy_version==="candidate_policy_v2_daily_goal_ranking";
 const reasons=(run.exclusions??[]).filter(e=>relevantCategoryExclusion(e,cat)).reduce<Record<string,number>>((a,e)=>(a[e.reason]=(a[e.reason]??0)+1,a),{});
 return <details className="details"><summary>Seçim yöntemi ve eksik adayın nedeni</summary>
  {!ranked?<p>Bu kaydın kuralları: Olasılık ≥ {percent(kind==="DAILY_OVER_35"?.52:.64)} · oran &gt; 1,00 · EV &gt; 0 · oran yaşı ≤ 24 saat.</p>:<p>Geçerli oran, son 24 saatlik fiyat, doğrulanmış eşleşme ve yeterli geçmiş gerekir. Belirgin model kalitesi sorunu olanlar elenir. Kalanlar olasılık, EV, güven ve veri kalitesi sırasıyla sıralanır; ilk {kind==="DAILY_BTTS"?"5–7":"3–5"} maç seçilir. Sabit olasılık veya pozitif EV şartı yoktur; {kind==="DAILY_BTTS"?"beş":"üç"} geçerli maç yoksa kupon oluşmaz.</p>}
  {Object.entries(reasons).map(([key,n])=><div key={key}>{exclusionLabel(key)}: {n}</div>)}
 </details>;
}
