import { useState } from "react";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/tauri";
import type { CapabilityReadiness, SubsystemReadiness } from "../types";
import { localDate } from "../lib/format";
import { DataState } from "../components/States";
import { PageHeader } from "../components/Page";
import { StatusBadge } from "../components/StatusBadge";

export function DataCenterPage(){
 const state=useAsync(api.dataCenterStatus,[]),[operation,setOperation]=useState<string|null>(null),[actionError,setActionError]=useState<string|null>(null);
 const run=async(name:string,action:()=>Promise<unknown>)=>{setOperation(name);setActionError(null);try{await action();await state.reload()}catch(e){setActionError(e instanceof Error?e.message:String(e))}finally{setOperation(null)}};
 return <><PageHeader eyebrow="OPERASYONEL HAZIRLIK" title="Veri Merkezi" description="ARZ Predictor bugün güvenilir tahmin üretmeye hazır mı?" actions={<button className="button secondary" disabled={!!operation} onClick={state.reload}>Hazırlığı tekrar kontrol et</button>}/><DataState {...state} onRetry={state.reload}>{data=><><section className={`readiness-hero ${data.overall_status.toLowerCase()}`}><div><span className="eyebrow">GENEL DURUM</span><h2>{overallLabel(data.overall_status)}</h2><p>{data.first_run?"İlk kurulum için gerekli veri bileşenleri kontrol ediliyor.":overallMessage(data.overall_status)}</p></div><StatusBadge value={data.overall_status}/><div className="capabilities"><Capability label="Tahmin üretilebilir" value={data.can_generate_predictions}/><Capability label="Aday üretilebilir" value={data.can_generate_candidates}/><Capability label="Kupon üretilebilir" value={data.can_generate_coupons}/></div></section>{actionError&&<div className="action-error"><strong>İşlem tamamlanamadı.</strong><span>Mevcut yerel veriler kullanılmaya devam ediyor.</span><details><summary>Ayrıntı</summary>{actionError}</details></div>}<div className="manual-actions"><button className="button" disabled={!!operation} onClick={()=>run("iddaa",api.refreshIddaa)}>{operation==="iddaa"?"Güncelleniyor…":"İddaa verisini güncelle"}</button><button className="button secondary" disabled={!!operation} onClick={()=>run("popular",api.refreshPopularity)}>{operation==="popular"?"Güncelleniyor…":"Popülerleri güncelle"}</button><button className="button secondary" disabled={!!operation} onClick={()=>run("logos",async()=>{await api.scanLogos();await api.startLogoSync()})}>{operation==="logos"?"Kontrol ediliyor…":"Eksik logoları kontrol et"}</button><button className="button secondary" disabled={!!operation} onClick={()=>run("history",api.historicalStatus)}>Geçmiş veri durumunu kontrol et</button></div><div className="readiness-grid"><ReadinessCard item={data.iddaa} companion={data.odds}/><ReadinessCard item={data.historical_data}/><ReadinessCard item={data.prediction_model} companion={data.calibration}/><ReadinessCard item={data.lineup_model} companion={data.lineup_provider}/><ReadinessCard item={data.team_logos}/><ReadinessCard item={data.entity_resolution}/><ReadinessCard item={data.features}/><ReadinessCard item={data.database}/><ReadinessCard item={data.popularity}/></div><p className="checked-at">Son hazırlık kontrolü: {localDate(data.checked_at,true)}</p></>}</DataState></>
}
function Capability({label,value}:{label:string;value:CapabilityReadiness}){return <div title={value.reasons.join(" ")}><span className={`cap-dot ${value.ready?"yes":"no"}`}>{value.ready?"✓":"×"}</span><div><strong>{label}</strong><small>{value.ready?"Evet":value.reasons[0]??"Hayır"}</small></div></div>}
function ReadinessCard({item,companion}:{item:SubsystemReadiness;companion?:SubsystemReadiness}){return <section className="panel readiness-card"><header><div><h2>{item.title}</h2><span>{item.source}</span></div><StatusBadge value={item.status}/></header><p>{item.message}</p>{item.progress!=null&&<div className="progress"><i style={{width:`${Math.round(item.progress*100)}%`}}/><span>{Math.round(item.progress*100)}%</span></div>}<div className="readiness-facts">{Object.entries(item.metrics).slice(0,4).map(([key,value])=><span key={key}><small>{metricLabel(key)}</small><strong>{new Intl.NumberFormat("tr-TR").format(value)}</strong></span>)}{!Object.keys(item.metrics).length&&item.item_count!=null&&<span><small>Kayıt</small><strong>{new Intl.NumberFormat("tr-TR").format(item.item_count)}</strong></span>}{item.downloaded_bytes!=null&&<span><small>Yerel boyut</small><strong>{bytes(item.downloaded_bytes)}</strong></span>}{item.artifact_hash&&<span><small>Artefakt</small><strong>{item.artifact_hash}</strong></span>}<span><small>Son güncelleme</small><strong>{localDate(item.last_updated,true)}</strong></span></div>{companion&&<div className="companion"><div><strong>{companion.title}</strong><small>{companion.message}</small></div><StatusBadge value={companion.status}/></div>}{item.technical_reason&&<details><summary>Teknik ayrıntı</summary><code>{item.technical_reason}</code></details>}</section>}
const bytes=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const metricLabel=(key:string)=>({supported_datasets:"Desteklenen",cached_datasets:"Önbellekte",imported_datasets:"İçe aktarılan",missing_datasets:"Eksik",event_count:"Müsabaka",competition_count:"Lig",odds_snapshot_count:"Oran",item_count:"Seçim",total_known_teams:"Takım",cached_valid_logos:"Hazır logo",missing_logos:"Eksik logo",failed_or_corrupt_logos:"Hatalı logo",resolved_mapping_count:"Eşleşen",unresolved_count:"Çözülemeyen",features_generated:"Özellik",insufficient_history:"Yetersiz geçmiş"}[key]??key);
const overallLabel=(x:string)=>({READY:"Hazır",PARTIAL:"Bazı veriler eksik",ACTION_REQUIRED:"Müdahale gerekiyor",UPDATING:"Hazırlanıyor",ERROR:"Kontrol gerekli",UNAVAILABLE:"Kullanılamıyor"}[x]??x);
const overallMessage=(x:string)=>x==="READY"?"Tüm temel ve yardımcı bileşenler hazır.":x==="PARTIAL"?"Temel tahmin akışı kullanılabilir; yardımcı verilerin bir kısmı eksik.":x==="UPDATING"?"Bir veya daha fazla veri bileşeni arka planda güncelleniyor.":"Güvenilir tahmin için bazı temel bileşenlerin hazırlanması gerekiyor.";
