import { useState } from "react";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/tauri";
import type { Metric, OddsMetric, WindowKey } from "../types";
import { decimal, percent } from "../lib/format";
import { DataState, EmptyState } from "../components/States";
import { MetricCard, PageHeader, Section } from "../components/Page";
import { StatusBadge } from "../components/StatusBadge";

const windows: WindowKey[] = ["LAST_7_DAYS", "LAST_30_DAYS", "SEASON", "ALL_TIME"];
const markets: Record<string,string> = {MATCH_RESULT:"Maç sonucu",BTTS:"KG Var",TOTAL_GOALS:"Toplam gol",TEAM_TOTAL_GOALS:"Takım toplam gol",FULL_TIME_TOTAL_CORNERS:"Toplam korner",FULL_TIME_TOTAL_CARDS:"Toplam kart"};
export function ModelPerformancePage() {
  const [window,setWindow] = useState<WindowKey>("LAST_30_DAYS"), [market,setMarket] = useState(""), [context,setContext] = useState(""), [competition,setCompetition] = useState(0);
  const state = useAsync(() => api.modelPerformance(window,market,context,competition||undefined), [window,market,context,competition]);
  return <><PageHeader eyebrow="MODEL KALİTESİ" title="Model Performansı" description="Olasılıkların doğruluğu ve kalibrasyonu; finansal performanstan bağımsız." actions={<button className="button secondary" onClick={state.reload}>Yenile</button>}/><div className="filterbar"><select value={window} onChange={e=>setWindow(e.target.value as WindowKey)}>{windows.map(x=><option key={x} value={x}>{windowName(x)}</option>)}</select><select value={market} onChange={e=>setMarket(e.target.value)}><option value="">Tüm marketler</option>{Object.entries(markets).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={context} onChange={e=>setContext(e.target.value)}><option value="">Tüm bağlamlar</option><option value="BASE">BASE</option><option value="LINEUP_AWARE">11'ler sonrası</option></select><select value={competition} onChange={e=>setCompetition(Number(e.target.value))}><option value={0}>Tüm ligler</option>{state.data?.by_competition.filter((x,i,a)=>x.competition_id!=null&&a.findIndex(y=>y.competition_id===x.competition_id)===i).map(x=><option key={x.competition_id!} value={x.competition_id!}>{x.competition_name}</option>)}</select></div><DataState {...state} onRetry={state.reload}>{data=>data.sample_count===0?<EmptyState title="Bu filtre için yeterli sonuçlanmış örnek yok."/>:<><div className="metrics"><MetricCard label="Örnek" value={String(data.sample_count)} note={`${data.from_date??"İlk kayıt"} — ${data.to_date??"Bugün"}`}/><MetricCard label="Durum" value={statusName(data.status)}/><MetricCard label="Market" value={market?markets[market]??market:"Tümü"}/><MetricCard label="Bağlam" value={context||"BASE + 11'ler"}/></div><Section title="Genel görünüm"><MetricTable rows={data.overall}/></Section><div className="two-col analytics"><Section title="Güven aralıkları"><BucketList data={data.confidence_buckets}/></Section><Section title="BASE ve 11'ler sonrası">{data.base_vs_lineup.length?<div className="comparison-list">{data.base_vs_lineup.map(x=><div key={x.market}><div><strong>{markets[x.market]??x.market}</strong><StatusBadge value={x.status}/></div><span>N={x.paired_sample_count}</span><span>BASE Brier {decimal(x.base.brier_score,3)}</span><span>11'ler Brier {decimal(x.lineup_aware.brier_score,3)}</span></div>)}</div>:<EmptyState title="Karşılaştırma için yeterli eş örnek yok."/>}</Section></div><Section title="Markete göre"><MetricTable rows={data.by_market}/></Section><Section title="Lige göre"><MetricTable rows={data.by_competition}/></Section><Section title="Toplam oran aralıkları"><OddsTable rows={data.by_odds_range}/></Section><Section title="Model sürümleri"><MetricTable rows={data.by_model_version}/></Section></>}</DataState></>;
}
function MetricTable({rows}:{rows:Metric[]}){return rows.length?<div className="table-wrap"><table><thead><tr><th>Kırılım</th><th>Bağlam</th><th>N</th><th>Başarı</th><th>Brier</th><th>Kayıp</th><th>Kalibrasyon</th><th>Durum</th></tr></thead><tbody>{rows.map((x,i)=><tr key={`${x.market}-${x.competition_id}-${x.model_version}-${i}`}><td><strong>{x.competition_name??markets[x.market??""]??x.market??x.model_version}</strong></td><td><StatusBadge value={x.prediction_context}/></td><td>{x.sample_count}</td><td>{percent(x.accuracy??x.actual_hit_rate,1)}</td><td>{decimal(x.brier_score,3)}</td><td>{decimal(x.log_loss,3)}</td><td>{percent(x.calibration_error_ece,1)}</td><td><StatusBadge value={x.status}/></td></tr>)}</tbody></table></div>:<EmptyState title="Bu kırılım için veri yok."/>}
function OddsTable({rows}:{rows:OddsMetric[]}){return rows.length?<div className="table-wrap"><table><thead><tr><th>Oran aralığı</th><th>Market</th><th>Bağlam</th><th>N</th><th>Ort. olasılık</th><th>Gerçekleşme</th><th>Brier</th><th>Kayıp</th><th>Durum</th></tr></thead><tbody>{rows.map((x,i)=><tr key={`${x.odds_range}-${x.market}-${i}`}><td><strong>{x.odds_range}</strong></td><td>{markets[x.market]??x.market}</td><td><StatusBadge value={x.prediction_context}/></td><td>{x.sample_count}</td><td>{percent(x.average_predicted_probability,1)}</td><td>{percent(x.actual_hit_rate,1)}</td><td>{decimal(x.brier_score,3)}</td><td>{decimal(x.log_loss,3)}</td><td><StatusBadge value={x.status}/></td></tr>)}</tbody></table></div>:<EmptyState title="Oran aralığı verisi yok."/>}
function BucketList({data}:{data:{bucket:string;sample_count:number;average_predicted_probability:number;actual_hit_rate:number;calibration_gap:number}[]}){return data.length?<div className="bucket-list">{data.map((x,i)=><div key={`${x.bucket}-${i}`}><div><strong>{x.bucket}</strong><span>N={x.sample_count}</span></div><div className="bucket-track"><i style={{width:`${Math.min(100,x.average_predicted_probability*100)}%`}}/></div><span>Tahmin {percent(x.average_predicted_probability,1)} · Gerçek {percent(x.actual_hit_rate,1)} · Fark {percent(x.calibration_gap,1)}</span></div>)}</div>:<EmptyState title="Güven aralığı verisi yok."/>}
const windowName=(x:WindowKey)=>({LAST_7_DAYS:"Son 7 gün",LAST_30_DAYS:"Son 30 gün",SEASON:"Sezon",ALL_TIME:"Tüm zamanlar"}[x]);
const statusName=(x:string)=>({SUFFICIENT:"Yeterli",LOW_SAMPLE:"Düşük örnek",INSUFFICIENT_DATA:"Yetersiz veri"}[x]??x);
