import { useBusinessDate } from "../hooks/useBusinessDate";
import { dailySelections, selectedContext } from "../lib/dailySelections";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/tauri";
import { decimal, localDate } from "../lib/format";
import { DataState, EmptyState } from "../components/States";
import { MatchRow } from "../components/MatchRow";
import { MetricCard, PageHeader, Section } from "../components/Page";
import { StatusBadge } from "../components/StatusBadge";
export function TodayPage(){
 const date=useBusinessDate();
 const state=useAsync(async()=>{const [matches,coupons,bulletin,readiness,run]=await Promise.all([api.dailyMatches(date),api.coupons(date),api.bulletinStatus(),api.currentReadiness(),api.candidates(date).catch(e=>{if(e.message==='no candidate run')return null;throw e})]);return{matches,coupons,bulletin,readiness,run}},[date]);
 return <><PageHeader eyebrow="OPERASYON ÖZETİ" title="Bugün" description="Günün model fırsatları, kuponları ve veri hazırlığı tek görünümde." actions={<button className="button secondary" onClick={state.reload}>Yenile</button>}/><DataState {...state} onRetry={state.reload}>{({matches,run,coupons,bulletin,readiness})=>{const today=matches.filter(m=>m.status==="scheduled"&&new Date(m.kickoff_at).getTime()>Date.now()&&new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(m.kickoff_at))===date),candidates=run?dailySelections(run,"TÜMÜ"):[];return <>{!readiness.can_generate_predictions.ready&&<div className="today-readiness"><StatusBadge value={readiness.overall_status}/><div><strong>Tahmin hazırlığı tamamlanmadı</strong><span>{readiness.can_generate_predictions.reasons[0]}</span></div><small>Detaylar ve güvenli işlemler Veri Merkezi’nde.</small></div>}<div className="metrics"><MetricCard label="Bugünkü maç" value={String(today.length)}/><MetricCard label="Günlük seçim" value={String(candidates.length)} note={run?`${selectedContext(run)} · ${run.publication_id}`:"Koşu bekleniyor"}/><MetricCard label="Hazır kupon" value={String(coupons.filter(c=>c.publication_status==="READY").length)}/><MetricCard label="Son oran verisi" value={localDate(bulletin.latest_odds_snapshot_time)}/></div><div className="two-col"><Section title="Öne çıkan fırsatlar" meta={<StatusBadge value={run?selectedContext(run):undefined}/>}><div className="compact-list">{candidates.length?candidates.slice(0,6).map(c=><MatchRow key={c.id} candidate={c} match={matches.find(m=>m.match_id===c.match_id)}/>):<EmptyState title="Bugün yeterli güvene sahip aday yok."/>}</div></Section><div className="stack"><Section title="Günün kuponları"><div className="coupon-mini-list">{coupons.some(c=>c.publication_status==="READY")?coupons.filter(c=>c.publication_status==="READY").map(c=><div className="coupon-mini" key={c.id}><div><strong>{couponName(c.coupon_type)}</strong><small>{c.selections.length} seçim · {decimal(c.combined_decimal_odd)} oran</small></div><StatusBadge value={c.publication_status}/></div>):<EmptyState title="Bugün kriterleri karşılayan kupon oluşturulamadı."/>}</div></Section><Section title="Veri hazırlığı"><div className="readiness"><Readiness label="İddaa" value={statusText(readiness.iddaa.status)} ok={readiness.iddaa.status==="READY"}/><Readiness label="Model" value={statusText(readiness.prediction_model.status)} ok={readiness.prediction_model.status==="READY"}/><Readiness label="11 sağlayıcısı" value={statusText(readiness.lineup_provider.status)} ok={readiness.lineup_provider.status==="READY"}/><Readiness label="Oran tazeliği" value={localDate(bulletin.latest_odds_snapshot_time,true)} ok={readiness.odds.status==="READY"}/></div></Section></div></div></>}}</DataState></>
}
const couponName=(v:string)=>({DAILY_CORNERS:"Korner",DAILY_OVER_25:"2.5 Üst",DAILY_OVER_35:"3.5 Üst",DAILY_BTTS:"KG Var",DAILY_HIGH_CONFIDENCE:"Yüksek Güven",DAILY_SURPRISE_SYSTEM:"Sürpriz Sistem",DAILY_COMPOUND:"Katlama"}[v]??v);
const statusText=(v:string)=>({READY:"Hazır",PARTIAL:"Kısmen hazır",ACTION_REQUIRED:"İşlem gerekiyor",UPDATING:"Güncelleniyor",UNAVAILABLE:"Kullanılamıyor",ERROR:"Hata"}[v]??v);
function Readiness({label,value,ok}:{label:string;value:string;ok:boolean}){return <div><span className={`health-dot ${ok?"online":"offline"}`}/><span>{label}</span><strong>{value}</strong></div>}
