export type WindowKey = "LAST_7_DAYS" | "LAST_30_DAYS" | "SEASON" | "ALL_TIME";
export type PredictionContext = "BASE" | "LINEUP_AWARE";
export type Reliability = "SUFFICIENT" | "LOW_SAMPLE" | "INSUFFICIENT_DATA";

export interface DatabaseHealth { status: string; database_path: string; foreign_keys_enabled: boolean; applied_migrations: number }
export interface DatabaseStats { competitions:number; teams:number; matches:number; match_statistics:number; odds_snapshots:number; predictions:number; model_versions:number; popularity_snapshots:number; coupons:number }
export interface BulletinStatus { last_successful_refresh:string|null; upcoming_match_count:number; competition_count:number; team_count:number; latest_odds_snapshot_time:string|null; odds_snapshot_count:number; unresolved_competition_count:number }
export interface PopularityStatus { last_successful_refresh:string|null; snapshot_count:number; latest_snapshot_time:string|null; latest_selection_count:number; matched_selection_count:number; unmatched_selection_count:number }
export interface UpcomingMatch { match_id:number; provider_event_id:string; competition_id:number; competition:string; kickoff_at:string; home_team_id:number; home_team:string; away_team_id:number; away_team:string; available_markets:number }
export interface LatestOdd { match_id:number; normalized_market_type:string; normalized_selection:string|null; selection:string; line:number|null; odd:number; captured_at:string }

export interface Candidate { id:number; match_id:number; competition_id:number; category:string; market:string; selection:string; line:number|null; public_probability:number; iddaa_odd:number; probability_edge:number; expected_value:number; qualification_state:string; prediction_source:string|null; base_public_probability:number|null; final_public_probability:number|null; delta_percentage_points:number|null; lineup_family_status:string|null }
export interface DailyRun { run_id:number; business_date:string; generated_at:string; model_version:string; calibration_version:string|null; match_count_considered:number; candidates:Candidate[]; prediction_context:string|null; lineup_aware_match_count:number; base_fallback_match_count:number }
export interface CandidateStatus { active_model_version:string|null; calibration_version:string|null; business_date:string|null; latest_run_id:number|null; latest_generation_time:string|null; matches_eligible_today:number; qualified_counts:Record<string,number>; missing_odds_count:number; stale_odds_count:number; model_unavailable_count:number }

export interface CouponSelection { candidate_id:number; match_id:number; competition_id:number; market:string; selection:string; line:number|null; public_probability:number; odd:number; edge:number; expected_value:number; status:string }
export interface SystemColumn { column_number:number; system_size:number; candidate_ids:number[]; column_decimal_odd:number; status:string }
export interface Coupon { id:number; coupon_type:string; business_date:string; status:string; selections:CouponSelection[]; system_sizes:number[]; columns:SystemColumn[]; combined_decimal_odd:number|null; unit_stake_cents:number|null; total_stake_cents:number|null; series_id:number|null; step_number:number|null }
export interface CompoundSeriesStep { step_number:number; coupon_id:number; business_date:string; stake_cents:number; combined_odd:number; result:string; settled_at:string|null }
export interface CompoundSeries { id:number; business_date:string; status:string; current_step:number; starting_stake_cents:number; current_stake_cents:number; completed_steps:number; latest_coupon_id:number|null; reset_count:number; history:CompoundSeriesStep[] }
export interface LineupImpactItem { match_id:number; market:string; selection:string; line:number|null; base_probability:number; latest_probability:number; delta_percentage_points:number; impact_type:string; prediction_source:string; family_status:string|null }
export interface LineupImpact { revision_available:boolean; affected_selection_count:number; items:LineupImpactItem[] }

export interface PopularItem { popularity_rank:number; total_played:number; total_played_round_str:string|null; match_id:number|null; kickoff:string|null; competition:string|null; home_team:string|null; away_team:string|null; market:string; selection:string; line:number|null; odds:number|null; model_probability:number|null; edge:number|null; expected_value:number|null; qualified:boolean|null; support_status:string; prediction_context:string|null; prediction_source:string|null; reason:string|null }
export interface PopularResponse { business_date:string; popularity_snapshot_at:string|null; prediction_context:string|null; total_popular_items:number; model_supported_items:number; items:PopularItem[] }

export interface Metric { prediction_context:PredictionContext; metric_type:string; market:string|null; competition_id:number|null; competition_name:string|null; model_version:string; sample_count:number; status:Reliability; average_predicted_probability:number|null; actual_hit_rate:number|null; accuracy:number|null; brier_score:number|null; log_loss:number|null; calibration_error_ece:number|null }
export interface ConfidenceBucket { bucket:string; sample_count:number; status:Reliability; average_predicted_probability:number; actual_hit_rate:number; calibration_gap:number; brier_score:number }
export interface OddsMetric { prediction_context:PredictionContext; market:string; model_version:string; odds_range:string; sample_count:number; status:Reliability; average_predicted_probability:number; actual_hit_rate:number; brier_score:number; log_loss:number; calibration_error_ece:number|null }
export interface ContextComparison { market:string; paired_sample_count:number; status:Reliability; base:Metric; lineup_aware:Metric; brier_delta_lineup_minus_base:number|null; log_loss_delta_lineup_minus_base:number|null }
export interface ModelPerformance { window:WindowKey; from_date:string|null; to_date:string|null; sample_count:number; status:Reliability; overall:Metric[]; by_market:Metric[]; confidence_buckets:ConfidenceBucket[]; by_competition:Metric[]; by_odds_range:OddsMetric[]; by_model_version:Metric[]; base_vs_lineup:ContextComparison[] }

export interface FinancialSummary { coupon_count:number; settled_count:number; won_count:number; lost_count:number; void_count:number; hit_rate:number|null; total_stake_cents:number; total_gross_return_cents:number; total_net_pnl_cents:number; roi:number|null; average_stake_cents:number|null; average_combined_odds:number|null }
export interface CouponTypePerformance extends FinancialSummary { coupon_type:string }
export interface OddsBandPerformance extends FinancialSummary { odds_band:string }
export interface SystemSummary { system_coupon_count:number; settled_system_coupon_count:number; total_columns:number; winning_columns:number; losing_columns:number; void_columns:number; total_stake_cents:number; total_gross_return_cents:number; net_pnl_cents:number; roi:number|null }
export interface KatlamaStep { step:number; attempts:number; wins:number; losses:number; voids:number; hit_rate:number|null }
export interface KatlamaSummary { sequences_started:number; active_sequences:number; failed_sequences:number; completed_sequences:number; average_reached_step:number|null; highest_reached_step:number|null; total_initial_stake_cents:number; realized_initial_stake_cents:number; total_realized_return_cents:number; net_pnl_cents:number; roi:number|null; by_step:KatlamaStep[] }
export interface CouponPerformance { window:WindowKey; from_date:string|null; to_date:string; financial_mode:"REALIZED"; overall:FinancialSummary; by_coupon_type:CouponTypePerformance[]; by_odds_band:OddsBandPerformance[]; system_summary:SystemSummary|null; katlama_summary:KatlamaSummary|null }

export type ReadinessState="READY"|"PARTIAL"|"ACTION_REQUIRED"|"UPDATING"|"UNAVAILABLE"|"ERROR";
export interface SubsystemReadiness { status:ReadinessState; title:string; message:string; last_updated:string|null; progress:number|null; item_count:number|null; metrics:Record<string,number>; downloaded_bytes:number|null; source:string|null; retryable:boolean; technical_reason:string|null; artifact_hash:string|null }
export interface CapabilityReadiness { ready:boolean; reasons:string[] }
export interface DataCenterStatus { overall_status:ReadinessState; first_run:boolean; checked_at:string; database:SubsystemReadiness; historical_data:SubsystemReadiness; iddaa:SubsystemReadiness; odds:SubsystemReadiness; popularity:SubsystemReadiness; team_logos:SubsystemReadiness; entity_resolution:SubsystemReadiness; features:SubsystemReadiness; prediction_model:SubsystemReadiness; calibration:SubsystemReadiness; lineup_model:SubsystemReadiness; lineup_provider:SubsystemReadiness; can_generate_predictions:CapabilityReadiness; can_generate_candidates:CapabilityReadiness; can_generate_coupons:CapabilityReadiness }
export interface LicenseStatus { state:string; plan:string|null; license_id:string|null; activated_at:string|null; expires_at:string|null; last_verified_at:string|null; device_bound:boolean; offline_grace_until:string|null; message:string }
